name: JetWare
motto: !ruby/object:StringML
  en: customized runtime environments for web applications
  ru: конструируемые рабочие окружения для веб-приложений
copyright: '&copy; 2016 <a href=/contacts>Jetware team</a>'
